# -*- coding: utf-8 -*-
"""16_12_2025_Python_kimya_paketleri_denemesi_pinn_Denemesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158mLtSwFk2JwLpV9jZRYATM0Qmz3swNw
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import os
from google.colab import drive

# Rastgelelik tohumlarını sabitle (Tekrarlanabilirlik için)
torch.manual_seed(42)
np.random.seed(42)

def pinn_simulation():

    file_path = '/content/drive/MyDrive/chemical_thesis_repo/16_12_2025_Calismalar/16_12_2025_python_ortami_denemesi/Muller_2024_H2_Sandstone_at_25C.txt'

    print(f"Veri okunuyor: {file_path}")
    if not os.path.exists(file_path):
        print("HATA: Dosya bulunamadı.")
        return

    # Veriyi yükle ve Tensor'a çevir
    raw_data = np.loadtxt(file_path, comments='%', encoding='latin1')
    t_exp = raw_data[:, 0:1] # (N, 1) şekline getir

    # H2, CO2, CH4, H2S (uM -> mM) ve SO4 (zaten mM)
    # Diğer biomass vs. verisi olmadığı için sadece bu 5'i ile Data Loss hesabı yapacağız
    data_vals = np.column_stack((raw_data[:, 1:5] * 1e-3, raw_data[:, 6]))

    # PyTorch Tensorlarına çevir (GPU varsa oraya at)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"İşlem birimi: {device}")

    t_data_torch = torch.tensor(t_exp, dtype=torch.float32, requires_grad=True).to(device)
    c_data_torch = torch.tensor(data_vals, dtype=torch.float32).to(device)

    # Colocation Points (Fizik denkleminin kontrol edileceği ara zaman noktaları)
    # 0'dan 20. güne kadar 2000 nokta
    t_physics = torch.linspace(0, 20, 2000).view(-1, 1).to(device)
    t_physics.requires_grad = True

    # ---------------------------------------------------------
    # 2. PINN MODELİ (Neural Network)
    # ---------------------------------------------------------
    class PINN(nn.Module):
        def __init__(self):
            super(PINN, self).__init__()
            # Girdi: Zaman (1)
            # Çıktı: 10 Bileşen (H2, CO2, CH4, H2S, SO4, FeS, X_m, X_s, X_a, Acetate)
            self.net = nn.Sequential(
                nn.Linear(1, 64),
                nn.Tanh(), # Türevlenebilir aktivasyon fonksiyonu şart
                nn.Linear(64, 64),
                nn.Tanh(),
                nn.Linear(64, 64),
                nn.Tanh(),
                nn.Linear(64, 10),
                nn.Softplus() # Konsantrasyonlar asla negatif olamaz! (Relu'nun yumuşağı)
            )

        def forward(self, t):
            return self.net(t)

    model = PINN().to(device)
    # Optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    # ---------------------------------------------------------
    # 3. FİZİK BİLGİSİ (ODEs in PyTorch)
    # ---------------------------------------------------------
    # Önceki Global Optimizasyondan bulduğumuz "En İyi" parametreleri sabitliyoruz.
    # Model bu parametreleri referans alacak ama veriye uymak için esneyecek.
    p = [3.41e-02, 1.38e-01, 6.54e-03, 0.42, 0.42, 0.42, 5.75, 1.0e-3, 9.72, 0.98, 8.3e-3, 0.99, -27.4]

    def physics_loss(model, t):
        # 1. Tahmin Yap
        y = model(t)

        # Değişkenleri ayır
        H2      = y[:, 0:1]; CO2     = y[:, 1:2]; CH4     = y[:, 2:3]
        H2S     = y[:, 3:4]; SO4     = y[:, 4:5]; FeS     = y[:, 5:6]
        X_meth  = y[:, 6:7]; X_sulf  = y[:, 7:8]; X_aceto = y[:, 8:9]; Acetate = y[:, 9:10]

        # 2. Otomatik Türev Al (dC/dt - Neural Network'ün eğimi)
        dydt_pred = torch.autograd.grad(y, t, torch.ones_like(y), create_graph=True)[0]

        # 3. Mekanistik Denklemden Beklenen Türevi Hesapla
        # Parametreleri aç
        k_m, k_s, k_a = p[0], p[1], p[2]
        Y_m, Y_s, Y_a = p[3], p[4], p[5]
        KI_m, KI_s, KI_a = p[6], p[7], p[8]
        k_precip, H2S_sat, H2_thr, DG_thr = p[9], p[10], p[11], p[12]

        R = 8.314e-3; T = 298.15; RT = R * T
        DG0_m = -130; DG0_s = -152; DG0_a = -95
        eps = 1e-6 # Log hatası önleyici

        # Termodinamik & Kinetik Hesaplar (Torch işlemleri ile)
        f_inh_m  = KI_m / (KI_m + H2S + eps)
        f_inh_s  = KI_s / (KI_s + H2S + eps)
        f_inh_a  = KI_a / (KI_a + H2S + eps)
        f_act    = H2 / (H2 + H2_thr + eps)

        Q_m = (CH4+eps) / ((H2+eps)**4 * (CO2+eps) + eps)
        Q_s = (H2S+eps) / ((H2+eps)**4 * (SO4+eps) + eps)
        Q_a = (Acetate+eps) / ((H2+eps)**4 * (CO2+eps)**2 + eps)

        DG_m = DG0_m + RT * torch.log(Q_m)
        DG_s = DG0_s + RT * torch.log(Q_s)
        DG_a = DG0_a + RT * torch.log(Q_a)

        f_thermo_m = 1 / (1 + torch.exp((DG_m - DG_thr)/RT))
        f_thermo_s = 1 / (1 + torch.exp((DG_s - DG_thr)/RT))
        f_thermo_a = 1 / (1 + torch.exp((DG_a - DG_thr)/RT))

        # Reaksiyon Hızları
        r_m = k_m * H2 * (CO2+eps)**(-2) * f_inh_m * f_act * f_thermo_m
        r_s = k_s * H2 * SO4 * f_inh_s * f_act * f_thermo_s
        r_a = k_a * H2 * (CO2+eps)**2 * f_inh_a * f_act * f_thermo_a
        r_p = k_precip * torch.relu(H2S - H2S_sat) # max(0, x) -> relu(x)

        # Beklenen Türevler (RHS of ODE)
        dH2_dt = -4*r_m - 4*r_s - 4*r_a
        dCO2_dt = -1*r_m - 2*r_a
        dCH4_dt = +1*r_m
        dH2S_dt = +1*r_s - r_p
        dSO4_dt = -1*r_s
        dFeS_dt = +1*r_p
        dXm_dt  = Y_m * r_m
        dXs_dt  = Y_s * r_s
        dXa_dt  = Y_a * r_a
        dAc_dt  = +1*r_a

        dydt_target = torch.cat([dH2_dt, dCO2_dt, dCH4_dt, dH2S_dt, dSO4_dt, dFeS_dt, dXm_dt, dXs_dt, dXa_dt, dAc_dt], dim=1)

        # Physics Loss: NN türevi ile Denklem türevi arasındaki fark (MSE)
        return torch.mean((dydt_pred - dydt_target)**2)

    # ---------------------------------------------------------
    # 4. EĞİTİM DÖNGÜSÜ
    # ---------------------------------------------------------
    print("PINN Eğitimi Başlıyor...")
    epochs = 10000 # İterasyon sayısı

    loss_history = []

    for epoch in range(epochs):
        optimizer.zero_grad()

        # A) Data Loss: Sadece deney noktalarında (t_data) hata hesapla
        # Modelin sadece ilk 5 çıktısı (H2, CO2, CH4, H2S, SO4) deneyle karşılaştırılır
        predictions_at_data = model(t_data_torch)
        loss_data = torch.mean((predictions_at_data[:, 0:5] - c_data_torch)**2)

        # B) Physics Loss: Tüm zaman aralığında (t_physics) denklemi kontrol et
        loss_ode = physics_loss(model, t_physics)

        # C) Toplam Hata (Weighted Sum)
        # Burada "Hile" yapıyoruz: Veri hatasına (loss_data) muazzam bir ağırlık veriyoruz.
        # Bu, modeli "Ne yaparsan yap o siyah noktalardan geç!" diye zorlar.
        # Fizik hatası ise "Noktaların arasını denkleme uygun doldur" der.
        total_loss = 1000.0 * loss_data + 1.0 * loss_ode

        total_loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}: Total Loss {total_loss.item():.4f} (Data: {loss_data.item():.4f}, ODE: {loss_ode.item():.4f})")
            loss_history.append(total_loss.item())

    # ---------------------------------------------------------
    # 5. SONUÇLARI GÖRSELLEŞTİR
    # ---------------------------------------------------------
    with torch.no_grad():
        t_plot = torch.linspace(0, 20, 200).view(-1, 1).to(device)
        y_plot = model(t_plot).cpu().numpy()
        t_plot_np = t_plot.cpu().numpy()

    species_names = ['H2', 'CO2', 'CH4', 'H2S', 'SO4']
    data_exp_np = c_data_torch.cpu().detach().numpy()
    t_exp_np = t_data_torch.cpu().detach().numpy()

    plt.figure(figsize=(15, 10))
    for i in range(5):
        plt.subplot(2, 3, i+1)
        # Deney Verisi
        plt.plot(t_exp_np, data_exp_np[:, i], 'ko', markersize=8, label='Deneysel')
        # PINN Tahmini
        plt.plot(t_plot_np, y_plot[:, i], 'r-', linewidth=2.5, label='PINN')

        plt.title(species_names[i])
        plt.xlabel('Time (Days)')
        plt.ylabel('Concentration (mM)')
        plt.grid(True, alpha=0.3)
        if i == 0: plt.legend()

    plt.suptitle('PINN Sonuçları: Data-Driven Fiziksel Model', fontsize=16)
    plt.tight_layout()
    plt.show()




    from scipy.io import savemat

    # PINN ile 2000 adımlık mükemmel simülasyon yap
    t_final = torch.linspace(0, 20, 2000).view(-1, 1).to(device)
    y_final = model(t_final).cpu().detach().numpy()

    # Matlab formatında kaydet
    # Matlab kodu transpoze (10 x Zaman) beklediği için .T (transpoze) alıyoruz
    savemat('PINN_Perfect_Data.mat', {'xTrain': y_final.T, 't': t_final.cpu().numpy().T})

    print("PINN verisi 'PINN_Perfect_Data.mat' olarak kaydedildi. Bunu indirip Matlab klasörüne at!")

if __name__ == "__main__":
    pinn_simulation()

