# -*- coding: utf-8 -*-
"""16_12_2025_Python_kimya_paketleri_denemesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtnRb6Iv2pGwgHTpJWJKIyBDB1YFnLJZ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy.optimize import least_squares
import warnings
import os
import sys
from google.colab import drive

# Uyarıları gizle
warnings.filterwarnings("ignore")

def mechanistic_model_py():

    file_path = '/content/drive/MyDrive/chemical_thesis_repo/16_12_2025_Calismalar/16_12_2025_python_ortami_denemesi/Muller_2024_H2_Sandstone_at_25C.txt'  # <--- BURAYI GÜNCELLEYİN

    # ---------------------------------------------------------

    print(f"\nVeri okunuyor: {file_path}")

    if not os.path.exists(file_path):
        print(f"HATA: '{file_path}' dosyası bulunamadı!")
        print("Lütfen 'file_path' değişkenine dosyanın tam yolunu (path) doğru yazdığınızdan emin olun.")
        return

    try:
        raw_data = np.loadtxt(file_path, comments='%', encoding='latin1')
    except Exception as e:
        print(f"Dosya okuma hatası: {e}")
        return

    # Sütunlar: Time(0), H2(1), CO2(2), CH4(3), H2S(4), pH(5), SO4(6)
    t_exp = raw_data[:, 0]

    # Birim Dönüşümü (µmol -> mM)
    data_exp = np.column_stack((raw_data[:, 1:5] * 1e-3, raw_data[:, 6]))

    # Başlangıç Koşulları (x0)
    x0 = np.concatenate([data_exp[0, :], [0.01, 0.01, 0.01, 0.0, 0.0]])

    # ---------------------------------------------------------
    # 2. Parametre Ayarları (Bounds & Initial Guess)
    # ---------------------------------------------------------
    p0 = np.array([1, 1, 1, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.01, 0.01, 0.01, -10])
    lb = np.array([0.001, 0.001, 0.001, 0.01, 0.01, 0.01, 0.001, 0.001, 0.001, 0, 0, 0, -50])
    ub = np.array([10, 10, 10, 0.5, 0.5, 0.5, 10, 10, 10, 1, 1, 1, 0])

    print("Parametre optimizasyonu (Fitting) başlıyor... (Bu işlem 1-2 dakika sürebilir)")

    # ---------------------------------------------------------
    # 3. Optimizasyon
    # ---------------------------------------------------------
    res_opt = least_squares(
        residuals_multiguild,
        p0,
        bounds=(lb, ub),
        args=(t_exp, data_exp, x0),
        method='trf',
        verbose=1,
        ftol=1e-6,
        xtol=1e-6,
        gtol=1e-6,
        max_nfev=5000
    )

    p_fit = res_opt.x
    print("\nBulunan Parametreler (p_fit):")
    print(p_fit)

    # ---------------------------------------------------------
    # 4. Sonuç Simülasyonu ve Çizim
    # ---------------------------------------------------------
    t_sim = np.linspace(0, t_exp[-1], 2000)

    sol = solve_ivp(
        lambda t, y: trueODEfunc_multiguild(t, y, p_fit),
        [0, t_exp[-1]],
        x0,
        t_eval=t_sim,
        method='Radau',
        rtol=1e-3,
        atol=1e-6
    )

    y_sim = sol.y.T

    # Grafikler
    species_names = ['H2', 'CO2', 'CH4 (Metan)', 'H2S (Sülfür)', 'SO4']

    plt.figure(figsize=(15, 10))
    for i in range(5):
        plt.subplot(2, 3, i+1)
        # Deneysel Veri
        plt.plot(t_exp, data_exp[:, i], 'ko', markersize=6, label='Deneysel' if i==0 else "")
        # Model
        if y_sim.shape[0] == len(t_sim):
            plt.plot(t_sim, y_sim[:, i], 'b-', linewidth=2, label='Model (Python)' if i==0 else "")

        plt.title(species_names[i])
        plt.xlabel('Zaman (Gün)')
        plt.ylabel('Konsantrasyon (mM)')
        plt.grid(True, alpha=0.3)
        if i == 0:
            plt.legend()

    plt.suptitle("Python Simülasyon Sonuçları (Drive Verisi & Stiff Solver)", fontsize=16)
    plt.tight_layout()
    plt.show()

# ---------------------------------------------------------
# Cost Function (Residuals)
# ---------------------------------------------------------
def residuals_multiguild(p, t_exp, data_exp, x0):
    try:
        sol = solve_ivp(
            lambda t, y: trueODEfunc_multiguild(t, y, p),
            [0, t_exp[-1]],
            x0,
            method='Radau',
            t_eval=t_exp,
            rtol=1e-3,
            atol=1e-6
        )

        if not sol.success or len(sol.t) < len(t_exp):
            return np.ones(data_exp.size) * 10.0

        y_sim = sol.y.T[:, 0:5]

        log_sim = np.log1p(y_sim)
        log_exp = np.log1p(data_exp)

        weights = np.array([1, 1, 0.5, 0.5, 1])

        res = (log_sim - log_exp) * weights
        res_flat = res.flatten()

        if np.isnan(res_flat).any():
            return np.ones(data_exp.size) * 10.0

        return res_flat

    except Exception:
        return np.ones(data_exp.size) * 10.0

# ---------------------------------------------------------
# ODE System (Mekanistik Model)
# ---------------------------------------------------------
def trueODEfunc_multiguild(t, y, p):
    y = np.maximum(0, y)

    H2      = y[0]
    CO2     = y[1]
    CH4     = y[2]
    H2S     = y[3]
    SO4     = y[4]
    FeS     = y[5]
    X_meth  = y[6]
    X_sulf  = y[7]
    X_aceto = y[8]
    Acetate = y[9]

    k_meth   = p[0]
    k_sulf   = p[1]
    k_aceto  = p[2]
    Y_m      = p[3]
    Y_s      = p[4]
    Y_a      = p[5]
    KI_meth  = p[6]
    KI_sulf  = p[7]
    KI_aceto = p[8]
    k_precip = p[9]
    H2S_sat  = p[10]
    H2_thresh= p[11]
    DG_thresh= p[12]

    R = 8.314e-3
    T = 298.15
    RT = R * T
    DG0_meth = -130
    DG0_sulf = -152
    DG0_aceto = -95

    eps = 1e-6
    H2_s      = max(H2, eps)
    CO2_s     = max(CO2, eps)
    CH4_s     = max(CH4, eps)
    SO4_s     = max(SO4, eps)
    H2S_s     = max(H2S, eps)
    Acetate_s = max(Acetate, eps)

    f_inh_meth  = KI_meth  / (KI_meth  + H2S)
    f_inh_sulf  = KI_sulf  / (KI_sulf  + H2S)
    f_inh_aceto = KI_aceto / (KI_aceto + H2S)

    f_activation = H2 / (H2 + H2_thresh)

    Q_meth  = CH4_s     / (H2_s**4 * CO2_s)
    Q_sulf  = H2S_s     / (H2_s**4 * SO4_s)
    Q_aceto = Acetate_s / (H2_s**4 * CO2_s**2)

    DG_meth  = DG0_meth  + RT * np.log(Q_meth)
    DG_sulf  = DG0_sulf  + RT * np.log(Q_sulf)
    DG_aceto = DG0_aceto + RT * np.log(Q_aceto)

    f_thermo_meth  = 1 / (1 + np.exp((DG_meth  - DG_thresh) / RT))
    f_thermo_sulf  = 1 / (1 + np.exp((DG_sulf  - DG_thresh) / RT))
    f_thermo_aceto = 1 / (1 + np.exp((DG_aceto - DG_thresh) / RT))

    r_meth  = k_meth  * H2 * (CO2_s**-2) * f_inh_meth  * f_activation * f_thermo_meth
    r_sulf  = k_sulf  * H2 * SO4      * f_inh_sulf  * f_activation * f_thermo_sulf
    r_aceto = k_aceto * H2 * (CO2**2) * f_inh_aceto * f_activation * f_thermo_aceto

    r_precip = k_precip * max(0, H2S - H2S_sat)

    dH2      = -4*r_meth - 4*r_sulf - 4*r_aceto
    dCO2     = -1*r_meth - 2*r_aceto
    dCH4     = +1*r_meth
    dH2S     = +1*r_sulf - r_precip
    dSO4     = -1*r_sulf
    dFeS     = +1*r_precip
    dX_meth  = Y_m * r_meth
    dX_sulf  = Y_s * r_sulf
    dX_aceto = Y_a * r_aceto
    dAcetate = +1*r_aceto

    return [dH2, dCO2, dCH4, dH2S, dSO4, dFeS, dX_meth, dX_sulf, dX_aceto, dAcetate]

if __name__ == "__main__":
    mechanistic_model_py()

